/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lojaeletronicos.forms;

/**
 *
 * @author Foto Claudia
 */
public class TelaPrincipal extends javax.swing.JFrame {
    CadastroCliente cadastroCliente;
    CadastroVendedor cadastroVendedor;
    CadastroProduto cadastroProduto;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
       cadastroCliente = new CadastroCliente();
       cadastroVendedor = new CadastroVendedor();
       cadastroProduto = new CadastroProduto();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        imgInicio = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        botaoCliente = new javax.swing.JMenu();
        bCadastrarCliente = new javax.swing.JMenuItem();
        bListarCliente = new javax.swing.JMenuItem();
        botaoVendedor = new javax.swing.JMenu();
        bCadastrarVendedor = new javax.swing.JMenuItem();
        botaoProduto = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja de Eletrônicos");

        jDesktopPane1.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleGradient"));

        imgInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojaeletronicos/imagens/Samsung-notebook-smartphone-e-tablet.png"))); // NOI18N

        jDesktopPane1.setLayer(imgInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(imgInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(imgInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(69, 69, 69))
        );

        botaoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojaeletronicos/imagens/cliente-icon-mini.png"))); // NOI18N
        botaoCliente.setText("Clientes");
        botaoCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClienteActionPerformed(evt);
            }
        });

        bCadastrarCliente.setText("Cadastrar");
        bCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarClienteActionPerformed(evt);
            }
        });
        botaoCliente.add(bCadastrarCliente);

        bListarCliente.setText("Listar Clientes");
        bListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarClienteActionPerformed(evt);
            }
        });
        botaoCliente.add(bListarCliente);

        jMenuBar1.add(botaoCliente);

        botaoVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojaeletronicos/imagens/vendedor-icon-mini.png"))); // NOI18N
        botaoVendedor.setText("Vendedores");
        botaoVendedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        bCadastrarVendedor.setText("Cadastrar");
        bCadastrarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarVendedorActionPerformed(evt);
            }
        });
        botaoVendedor.add(bCadastrarVendedor);

        jMenuBar1.add(botaoVendedor);

        botaoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojaeletronicos/imagens/prod-icon-mini.png"))); // NOI18N
        botaoProduto.setText("Produtos");
        botaoProduto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuBar1.add(botaoProduto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(1300, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void bCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        jDesktopPane1.add(cadastroCliente);
        cadastroCliente.setVisible(true);
    }                                                 

    private void botaoClienteActionPerformed(java.awt.event.ActionEvent evt) {                                             
        
    }                                            

    private void bListarClienteActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void bCadastrarVendedorActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        jDesktopPane1.add(cadastroVendedor);
        cadastroVendedor.setVisible(true);        
    }                                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem bCadastrarCliente;
    private javax.swing.JMenuItem bCadastrarVendedor;
    private javax.swing.JMenuItem bListarCliente;
    private javax.swing.JMenu botaoCliente;
    private javax.swing.JMenu botaoProduto;
    private javax.swing.JMenu botaoVendedor;
    private javax.swing.JLabel imgInicio;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration                   
}
