/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lojaeletronicos.forms;

/**
 *
 * @author Foto Claudia
 */
public class TelaIncial extends javax.swing.JFrame {
    CadastroCliente cadastroCliente;
    CadastroVendedor cadastroVendedor;
    CadastroProduto cadastroProduto;
    CadastroPedido cadastroPedido;
    /**
     * Creates new form TelaIncial
     */
    public TelaIncial() {
        cadastroCliente = new CadastroCliente();
        cadastroVendedor = new CadastroVendedor();
        cadastroProduto = new CadastroProduto();
        cadastroPedido = new CadastroPedido();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        cadCliente = new javax.swing.JMenuItem();
        menuVendedores = new javax.swing.JMenu();
        cadVendedor = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenu();
        cadProd = new javax.swing.JMenuItem();
        menuPedidos = new javax.swing.JMenu();
        cadPedido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja de Eletrônicos");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojaeletronicos/imagens/Samsung-notebook-smartphone-e-tablet.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente-icon-mini.png"))); // NOI18N
        menuClientes.setText("Clientes");

        cadCliente.setText("Cadastrar / Listar");
        cadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadClienteActionPerformed(evt);
            }
        });
        menuClientes.add(cadCliente);

        jMenuBar1.add(menuClientes);

        menuVendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendedor-icon-mini.png"))); // NOI18N
        menuVendedores.setText("Vendedores");

        cadVendedor.setText("Cadastrar / Listar");
        cadVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadVendedorActionPerformed(evt);
            }
        });
        menuVendedores.add(cadVendedor);

        jMenuBar1.add(menuVendedores);

        menuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prod-icon-mini.png"))); // NOI18N
        menuProdutos.setText("Produtos");

        cadProd.setText("Cadastrar / Listar");
        cadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadProdActionPerformed(evt);
            }
        });
        menuProdutos.add(cadProd);

        jMenuBar1.add(menuProdutos);

        menuPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lojaeletronicos/imagens/pedido-icon-mini.png"))); // NOI18N
        menuPedidos.setText("Pedidos");

        cadPedido.setText("Cadastar / Exibir ");
        cadPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPedidoActionPerformed(evt);
            }
        });
        menuPedidos.add(cadPedido);

        jMenuBar1.add(menuPedidos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadVendedorActionPerformed
         jDesktopPane1.add(cadastroVendedor);
          cadastroVendedor.setVisible(true);        
    }//GEN-LAST:event_cadVendedorActionPerformed

    private void cadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadProdActionPerformed
        jDesktopPane1.add(cadastroProduto);
          cadastroProduto.setVisible(true);
    }//GEN-LAST:event_cadProdActionPerformed

    private void cadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadClienteActionPerformed
        jDesktopPane1.add(cadastroCliente);
          cadastroCliente.setVisible(true);
    }//GEN-LAST:event_cadClienteActionPerformed

    private void cadPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadPedidoActionPerformed
        jDesktopPane1.add(cadastroPedido);
        cadastroPedido.setVisible(true);  
    }//GEN-LAST:event_cadPedidoActionPerformed
       

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIncial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIncial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIncial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIncial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaIncial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadCliente;
    private javax.swing.JMenuItem cadPedido;
    private javax.swing.JMenuItem cadProd;
    private javax.swing.JMenuItem cadVendedor;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuPedidos;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenu menuVendedores;
    // End of variables declaration//GEN-END:variables
}
